### ISSUE TITLE
Cannot change renderer

### ISSUE THREAD

**Issue by mattiash** [AlexxNB/svelte-preprocess-markdown#5]
I am trying to use a custom renderer, but i can't seem to make svelte-preprocess-markdown to actually use it. I tried following the instructions for getting the renderer in the README. My rollup.config.js looks like this:

```
import svelte from 'rollup-plugin-svelte';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import rollup_start_dev from './rollup_start_dev';
import {markdown, Renderer} from 'svelte-preprocess-markdown';

const renderer = Renderer();

renderer.hr = function() { return 'myhr' }

const production = !process.env.ROLLUP_WATCH;

export default {
	input: 'src/main.js',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/bundle.js'
	},
	plugins: [
		svelte({
			extensions: ['.svelte', '.md'],
			preprocess: markdown({
				renderer,
			}),
			// enable run-time checks when not in production
			dev: !production,
			// we'll extract any component CSS out into
			// a separate file — better for performance
			css: css => {
				css.write('public/bundle.css');
			}
		}),

		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration —
		// consult the documentation for details:
		// https://github.com/rollup/rollup-plugin-commonjs
		resolve({
			browser: true,
			dedupe: importee => importee === 'svelte' || importee.startsWith('svelte/')
		}),
		commonjs(),

		// In dev mode, call `npm run start:dev` once
		// the bundle has been generated
		!production && rollup_start_dev,

		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload('public'),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser()
	],
	watch: {
		clearScreen: false
	}
};
```

But my `---` sections still render as `<hr>` tags.

**Comment by AlexxNB** [comment]
Yeah, looks like the renderer option do nothing. I'll check tomorow.

**Comment by AlexxNB** [comment]
I've fixed it. (https://github.com/AlexxNB/svelte-preprocess-markdown/commit/6d770a8a844dd447fda81151fa198416d245ab03) New version already published on NPM.

**Comment by mattiash** [comment]
Works great. Thank you!

**Comment by ryanfiller** [comment]
I know this issue was closed in November, but I am having trouble getting this to work as well. My config is exactly as @mattiash initial post above but I am still not able to get this to render on any pages, `.svelte` or `.md`.

**Comment by AlexxNB** [comment]
Will check. There was huge Marked update in last commites. Maybe getting renderer has been broken.

**Comment by AlexxNB** [comment]
Just done installation default Svelte template with svelte-preprocess markdown and use config above. Everything works as a charm. Also added [the test](https://github.com/AlexxNB/svelte-preprocess-markdown/blob/master/tests/11-renderer.js) to check renderer function.
